# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Acierto
    url: https://www.acierto.com
  - name: Credimarket
    url: https://www.credimarket.com
  - name: Comparador seguros coche
    url: https://www.acierto.com/comparador.php
  - name: Comparador Prestamos
    url: https://www.acierto.com/prestamos/comparador/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://img1.acierto.com/css/r/images/logo-acierto.gif
  name: Upptime
  introTitle: "**Upptime** page de monitorizacion basica de servicios."
  introMessage: Esta pagina es una prueba temporal. No usar de referencia para ops.
  navbar:
    - title: Status
      href: /
    - title: Acierto
      href: https://www.acierto.com
    - title: Credimarket
      href: https://www.credimarket.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
